spring:
  datasource:
    username: concert_tracker
    password: concert_tracker
    url: jdbc:mysql://localhost:3306/concert_tracker
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  sql:
    init:
      mode: never